[package]
name = "codecrafters-claude-code"
version = "0.1.0"
authors = ["Codecrafters <hello@codecrafters.io>"]
edition = "2024"
rust-version = "1.95"

[dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread", "process", "fs", "signal"] }
async-openai = { version = "=0.32.4", features = ["byot", "chat-completion", "model"] }
clap = { version = "4.3.14", features = ["derive"] }
serde_json = "1.0.149"
serde = { version = "1.0.228", features = ["derive"] }
async-trait = "0.1"
thiserror = "2"
toml = "0.8"
glob = "0.3"
futures = "0.3"
rustyline = "14"
mlua = { version = "0.10", features = ["lua54", "vendored", "async", "send", "serialize"] }

[dev-dependencies]
tempfile = "3"
