//! Baseline session fixtures: fresh, long, compacted, resumed.
//!
//! Each one is generated by driving the real agent loop against a
//! scripted provider, then written to `tests/fixtures/ledger/<name>.json`
//! as the transcript and the ledger side by side — the pair a replay
//! harness needs to re-derive a run's accounting and compare it against
//! what this build produced.
//!
//! The user's own sessions cannot serve as the corpus: they carry no
//! token data, have never compacted, and are not ours to read. These are
//! synthetic and deterministic instead.
//!
//! Clock-dependent fields (timestamps, every `*_ms`) are zeroed before
//! comparison — a `ttft_ms` that is `null` still reads as `null`, since
//! "no first token to time" is a fact about the turn, not the clock.
//!
//! Regenerate with `OLI_UPDATE_FIXTURES=1 cargo test --lib baselines`.

use std::sync::Mutex;

use async_trait::async_trait;
use serde_json::{Value, json};
use tempfile::TempDir;

use super::{Ledger, PromptAccounting, RunIdentity, config_hash, ledger_path};
use crate::agent::Agent;
use crate::agent::memory::{Memory, PersistedMemory};
use crate::error::{AgentError, Result};
use crate::providers::{ChatRequest, ChatResponse, Provider, StreamEvent, StreamSink, Usage};
use crate::tools::{Registry, Tool, ToolContext};

/// Scripted provider that also replays per-call usage. `FakeProvider`
/// always reports `None`, which is exactly the case these fixtures are
/// not about.
struct ScriptedProvider {
    turns: Mutex<std::collections::VecDeque<(Value, Option<Usage>)>>,
}

impl ScriptedProvider {
    fn new(turns: Vec<(Value, Option<Usage>)>) -> Self {
        Self {
            turns: Mutex::new(turns.into()),
        }
    }
}

#[async_trait]
impl Provider for ScriptedProvider {
    async fn chat(&self, _req: ChatRequest) -> Result<ChatResponse> {
        let (message, usage) = self
            .turns
            .lock()
            .unwrap()
            .pop_front()
            .ok_or_else(|| AgentError::Provider("scripted provider exhausted".into()))?;
        Ok(ChatResponse { message, usage })
    }

    async fn chat_stream(&self, req: ChatRequest, sink: StreamSink<'_>) -> Result<ChatResponse> {
        let resp = self.chat(req).await?;
        if let Some(s) = resp.message.get("content").and_then(|v| v.as_str()) {
            if !s.is_empty() {
                sink(StreamEvent::Content(s));
            }
        }
        Ok(resp)
    }
}

struct Echo;

#[async_trait]
impl Tool for Echo {
    fn name(&self) -> &str {
        "Echo"
    }
    fn description(&self) -> &str {
        "echo back a fixed string"
    }
    fn parameters(&self) -> Value {
        json!({"type": "object", "properties": {}})
    }
    async fn run(&self, _args: Value, _ctx: &ToolContext) -> Result<String> {
        Ok("tool-output".into())
    }
}

fn usage(prompt: u32, completion: u32, cache_read: u32) -> Option<Usage> {
    Some(Usage {
        prompt_tokens: Some(prompt),
        completion_tokens: Some(completion),
        total_tokens: Some(prompt + completion),
        cache_read_tokens: Some(cache_read),
        cache_write_tokens: Some(0),
        reasoning_tokens: None,
    })
}

fn text(content: &str) -> Value {
    json!({"role": "assistant", "content": content})
}

fn tool_turn() -> Value {
    json!({
        "role": "assistant",
        "content": null,
        "tool_calls": [{
            "id": "c1",
            "type": "function",
            "function": {"name": "Echo", "arguments": "{}"}
        }]
    })
}

const MODEL: &str = "baseline-model";
const PROVIDER: &str = "baseline-provider";
const SESSION: &str = "baseline";

fn identity() -> RunIdentity {
    RunIdentity {
        session: SESSION.into(),
        provider: PROVIDER.into(),
        model: MODEL.into(),
        strategy: crate::bootstrap::MEMORY_STRATEGY.into(),
        strategy_version: crate::bootstrap::MEMORY_STRATEGY_VERSION,
        config_hash: config_hash(&json!({"model": MODEL, "max_turns": 8})),
    }
}

fn ledger_for(dir: &TempDir, resumed: bool) -> Ledger {
    Ledger::new(identity(), PromptAccounting::CacheInclusive)
        .with_sink(ledger_path(dir.path(), SESSION))
        .resumed(resumed)
}

fn tools() -> Registry {
    let mut r = Registry::new();
    r.register(Echo);
    r
}

/// Drive one run against a scripted provider inside `dir`, appending to
/// that directory's transcript and ledger.
async fn run_in(
    dir: &TempDir,
    script: Vec<(Value, Option<Usage>)>,
    prompts: &[&str],
    resumed: bool,
) -> Result<()> {
    let inner: Box<dyn Memory> = Box::new(crate::agent::LinearWithCompact::new());
    let mut persisted = PersistedMemory::open_at(dir.path(), SESSION, inner, true).await?;
    persisted
        .write_meta(json!({
            "provider": PROVIDER,
            "model": MODEL,
            "strategy": crate::bootstrap::MEMORY_STRATEGY,
            "config_hash": identity().config_hash,
        }))
        .await?;

    let mut agent = Agent::new(Box::new(ScriptedProvider::new(script)), tools(), MODEL.into())
        .with_memory(Box::new(persisted))
        .with_ledger(ledger_for(dir, resumed))
        .pin_system_prompt("you are a coding agent")
        .await?;
    for p in prompts {
        agent.run(p).await?;
    }
    agent.ledger.finish().await;
    Ok(())
}

fn collect(dir: &TempDir) -> Value {
    let read = |path: std::path::PathBuf| -> Vec<Value> {
        std::fs::read_to_string(path)
            .unwrap_or_default()
            .lines()
            .filter(|l| !l.trim().is_empty())
            .map(|l| serde_json::from_str(l).unwrap())
            .collect()
    };
    let mut out = json!({
        "transcript": read(dir.path().join(format!("{SESSION}.jsonl"))),
        "ledger": read(ledger_path(dir.path(), SESSION)),
    });
    normalize(&mut out);
    out
}

/// Zero every clock-dependent number. A `null` stays `null`: "nothing to
/// time" is a property of the turn, not of when the fixture was made.
fn normalize(v: &mut Value) {
    match v {
        Value::Object(map) => {
            for (k, value) in map.iter_mut() {
                if (k.ends_with("_ms") || k == "started_at_ms") && value.is_number() {
                    *value = json!(0);
                } else {
                    normalize(value);
                }
            }
        }
        Value::Array(items) => items.iter_mut().for_each(normalize),
        _ => {}
    }
}

fn fixture_path(name: &str) -> std::path::PathBuf {
    std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures/ledger")
        .join(format!("{name}.json"))
}

fn assert_fixture(name: &str, actual: &Value) {
    let path = fixture_path(name);
    let rendered = format!("{}\n", serde_json::to_string_pretty(actual).unwrap());
    if std::env::var_os("OLI_UPDATE_FIXTURES").is_some() {
        std::fs::create_dir_all(path.parent().unwrap()).unwrap();
        std::fs::write(&path, &rendered).unwrap();
        return;
    }
    let expected = std::fs::read_to_string(&path).unwrap_or_else(|e| {
        panic!(
            "missing baseline {}: {e}. Regenerate with OLI_UPDATE_FIXTURES=1.",
            path.display()
        )
    });
    assert_eq!(
        rendered,
        expected,
        "baseline {name} drifted. If the change is intended, regenerate \
         with OLI_UPDATE_FIXTURES=1 and review the diff."
    );
}

#[tokio::test]
async fn a_fresh_session_baseline_holds() {
    let dir = tempfile::tempdir().unwrap();
    run_in(
        &dir,
        vec![(text("the answer"), usage(120, 18, 0))],
        &["what is the answer?"],
        false,
    )
    .await
    .unwrap();
    assert_fixture("fresh", &collect(&dir));
}

#[tokio::test]
async fn a_long_session_baseline_holds() {
    let dir = tempfile::tempdir().unwrap();
    let mut script = Vec::new();
    let mut prompts = Vec::new();
    for i in 0..4 {
        script.push((tool_turn(), usage(200 + i * 40, 12, 0)));
        script.push((text("done"), usage(240 + i * 40, 20, 128)));
        prompts.push("keep going");
    }
    run_in(&dir, script, &prompts, false).await.unwrap();
    assert_fixture("long", &collect(&dir));
}

#[tokio::test]
async fn a_compacted_session_baseline_holds() {
    // `baseline-model` is unknown to the capability table, so it takes
    // the conservative 8k window and a 6.4k compaction target. Reporting
    // more than that drives the next turn through a compaction pass,
    // whose summary call consumes a scripted response of its own.
    let dir = tempfile::tempdir().unwrap();
    let script = vec![
        (text("one"), usage(1_000, 10, 0)),
        (text("two"), usage(2_000, 10, 0)),
        (text("three"), usage(7_000, 10, 0)),
        (text("a summary of the earlier turns"), None),
        (text("four"), usage(3_000, 10, 512)),
    ];
    run_in(&dir, script, &["a", "b", "c", "d"], false)
        .await
        .unwrap();
    let fixture = collect(&dir);
    // The point of this baseline: context attribution has a summary
    // bucket to attribute to.
    let summary_tokens: u64 = fixture["ledger"]
        .as_array()
        .unwrap()
        .iter()
        .filter(|r| r["kind"] == "request")
        .map(|r| r["estimated"]["summary"].as_u64().unwrap())
        .sum();
    assert!(summary_tokens > 0, "{fixture:#}");
    assert_fixture("compacted", &fixture);
}

#[tokio::test]
async fn a_resumed_session_baseline_holds() {
    let dir = tempfile::tempdir().unwrap();
    run_in(
        &dir,
        vec![
            (text("first"), usage(150, 12, 0)),
            (text("second"), usage(320, 14, 64)),
        ],
        &["open the file", "now change it"],
        false,
    )
    .await
    .unwrap();
    run_in(
        &dir,
        vec![(text("resumed answer"), usage(640, 20, 512))],
        &["carry on"],
        true,
    )
    .await
    .unwrap();

    let fixture = collect(&dir);
    // What resuming cost is the whole point of this baseline.
    let resumed_summary = fixture["ledger"]
        .as_array()
        .unwrap()
        .iter()
        .filter(|r| r["kind"] == "summary")
        .next_back()
        .unwrap()
        .clone();
    assert_eq!(resumed_summary["resumed"], true);
    assert_eq!(resumed_summary["first_request"]["uncached_input"], 128);
    assert_fixture("resumed", &fixture);
}
