use super::{SlashCommand, SlashOutcome};
use crate::agent::Agent;
use async_trait::async_trait;

/// `/paths` — print where every customization & state file lives on disk.
/// Each line is a real path resolved from the same code that loads the
/// file at startup, so it can't lie. Missing files get a `(not present)`
/// hint, which doubles as a how-to: touch the file to start customizing.
pub struct Paths;

#[async_trait]
impl SlashCommand for Paths {
    fn name(&self) -> &str {
        "paths"
    }
    fn description(&self) -> &str {
        "show on-disk locations for config, plugins, sessions, etc."
    }
    async fn run(&self, _args: &str, agent: &mut Agent) -> SlashOutcome {
        SlashOutcome::Continue(Some(render_paths(agent)))
    }
}

fn render_paths(agent: &Agent) -> String {
    let cwd = std::env::current_dir().unwrap_or_else(|_| std::path::PathBuf::from("."));
    let home = std::env::var_os("HOME").map(std::path::PathBuf::from);

    let mut out = String::new();

    // Working — the runtime state that frames everything else.
    out.push_str("# Working\n");
    out.push_str(&format!("  cwd:               {}\n", cwd.display()));
    let provider = if agent.provider_name.is_empty() {
        "(unset)"
    } else {
        agent.provider_name.as_str()
    };
    out.push_str(&format!("  active provider:   {}\n", provider));
    out.push_str(&format!("  active model:      {}\n", agent.model));

    // Customization — files the user edits to change behavior.
    out.push_str("\n# Customization\n");
    push_path(
        &mut out,
        "Global config",
        crate::config::default_config_path().as_deref(),
    );
    let project_cfg = cwd.join(".oli").join("config.toml");
    push_path(&mut out, "Project config", Some(&project_cfg));
    let cwd_agents = cwd.join("AGENTS.md");
    let cwd_claude = cwd.join("CLAUDE.md");
    push_path(&mut out, "Project AGENTS.md", Some(&cwd_agents));
    push_path(&mut out, "Project CLAUDE.md", Some(&cwd_claude));
    if let Some(h) = home.as_ref() {
        push_path(
            &mut out,
            "Global CLAUDE.md",
            Some(&h.join(".claude").join("CLAUDE.md")),
        );
        push_path(
            &mut out,
            "Global AGENTS.md",
            Some(&h.join(".codex").join("AGENTS.md")),
        );
    }
    out.push_str("  (oli also walks parent dirs of cwd looking for AGENTS.md/CLAUDE.md)\n");

    // Extensions — Lua plugin discovery dirs.
    out.push_str("\n# Extensions  (drop .lua files into a plugin dir)\n");
    let plugin_dirs = crate::plugins::default_plugin_dirs();
    for (i, p) in plugin_dirs.iter().enumerate() {
        let label = if p.is_absolute() {
            "Global plugins"
        } else {
            "Project plugins"
        };
        // Some installs may resolve the same path twice; key by index so
        // both lines render even if labels collide.
        let _ = i;
        push_dir(&mut out, label, p);
    }

    // State — generated by oli, listed for awareness rather than editing.
    out.push_str("\n# State\n");
    push_dir_opt(
        &mut out,
        "Sessions",
        crate::agent::memory::persisted::sessions_dir().as_deref(),
    );
    push_dir_opt(
        &mut out,
        "Notes",
        crate::notes::filesystem::FilesystemNotesStore::default_dir().as_deref(),
    );
    push_dir_opt(
        &mut out,
        "MCP OAuth credentials",
        crate::mcp::oauth::default_store_dir().as_deref(),
    );

    out.trim_end().to_string()
}

fn push_path(out: &mut String, label: &str, path: Option<&std::path::Path>) {
    let Some(p) = path else {
        out.push_str(&format!(
            "  {:<18} (no $HOME / $XDG_CONFIG_HOME)\n",
            format!("{}:", label)
        ));
        return;
    };
    let mark = if p.exists() { "" } else { "  (not present)" };
    out.push_str(&format!(
        "  {:<18} {}{}\n",
        format!("{}:", label),
        p.display(),
        mark
    ));
}

fn push_dir(out: &mut String, label: &str, path: &std::path::Path) {
    let mark = if path.is_dir() { "" } else { "  (not present)" };
    out.push_str(&format!(
        "  {:<18} {}/{}\n",
        format!("{}:", label),
        path.display(),
        mark
    ));
}

fn push_dir_opt(out: &mut String, label: &str, path: Option<&std::path::Path>) {
    match path {
        Some(p) => push_dir(out, label, p),
        None => out.push_str(&format!(
            "  {:<18} (no $HOME / $XDG_CONFIG_HOME)\n",
            format!("{}:", label)
        )),
    }
}
